image:
  file: .gitpod.Dockerfile

tasks:    
  - name: Postinstall Dotnet and certificates
    init: |
      mkdir -p $DOTNET_ROOT && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --install-dir $DOTNET_ROOT 
      dotnet dev-certs https 
      dotnet restore

vscode:
  extensions:
    - muhammad-sammy.csharp